version: "3.8"

services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
    restart: unless-stopped

  zap:
    image: zaproxy/zap-stable
    container_name: zap
    entrypoint: ["tail", "-f", "/dev/null"] # pour pouvoir exécuter des scans à la demande
    depends_on:
      - juice-shop
    restart: unless-stopped
